In [1]:
import numpy as np
A=np.arange(1,21).reshape(4,5)
print("A=\n",A)
print("dtype:",A.dtype)
print("ndim:",A.ndim) #الابعاد
print("shape:",A.shape)
print("size:",A.size)
print("itemsize:",A.itemsize)
B=A.reshape(5,4)
print("\nB=\n",B)
print("B.shape:",B.shape)
     
       

A=
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
dtype: int64
ndim: 2
shape: (4, 5)
size: 20
itemsize: 8

B=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
B.shape: (5, 4)


In [1]:
import numpy as np
a=np.array([[0.,0.,0.],
           [10.,10,10],
            [20,20,20],
            [30,30,30]])
b=np.array([0.,1.,2.])
c=a+b
print("c=\n",c)
mask=(c>=22)
print("\nmask=\n",mask)
count=mask.sum()
print("\ncount>=22:",count)
           

c=
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]

mask=
 [[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]

count>=22: 4


In [6]:
import numpy as np

# إنشاء المصفوفة
grades = np.array([
    [87, 96, 70],
    [100, 87, 90],
    [94, 77, 90],
    [100, 81, 82]
])

# العمليات العامة على كامل المصفوفة
print("Overall:")
print("Sum:",grades.sum())
print("Min:",grades.min())
print("Max:",grades.max())
print("Mean:",grades.mean())
print("Std:",grades.std())
print("Var:",grades.var())

# المتوسط لكل عمود (axis=0)
print("\nmean(axis=0) per column:",grades.mean(axis=0))
# المتوسط لكل صف (axis=1)
print("Mean (axis=1) per row:",grades.mean(axis=1))

# القيمة العظمى لكل صف (axis=1)
print("\nmax(axis=1) per row:",grades.max(axis=1))

Overall:
Sum: 1054
Min: 70
Max: 100
Mean: 87.83333333333333
Std: 8.792357792739987
Var: 77.30555555555556

mean(axis=0) per column: [95.25 85.25 83.  ]
Mean (axis=1) per row: [84.33333333 92.33333333 87.         87.66666667]

max(axis=1) per row: [ 96 100  94 100]


In [4]:
import numpy as np  #سوال 4
A=np.array([[2,4,6],
           [1,3,5],
           [7,9,11]])
print("Row sum:",A.sum(axis=1))
print("Column sum:",A.sum(axis=0))
print("Mean:",A.mean())

Row sum: [12  9 27]
Column sum: [10 16 22]
Mean: 5.333333333333333


In [6]:
import numpy as np
A=np.array([[10,20,30],
            [40,50,60]])
B=np.array([1,2,3])
print("A+B=\n",A+B)
print("\nA*2=\n",A*2)
print("\nA-5=\n",A-5)

A+B=
 [[11 22 33]
 [41 52 63]]

A*2=
 [[ 20  40  60]
 [ 80 100 120]]

A-5=
 [[ 5 15 25]
 [35 45 55]]


In [7]:
import numpy as np
grades = np.array([[70,85,90],
                   [88,76,94],
                   [60,80,72]])
print("argmax overall:",grades.argmax())
print("argmax per row:",grades.argmax(axis=1))
print("argmin per column:",grades.argmin(axis=0))

argmax overall: 5
argmax per row: [2 2 1]
argmin per column: [2 1 2]


In [13]:
import numpy as np 
def manhattan_distance(x1,y1,x2,y2):
   return abs(x2 - x1) + abs(y2 - y1)
def euclidean_distance(x1,y1,x2,y2):
   return np.abs((x2 - x1)**2 + (y2 - y1)**2)
