In [4]:
import numpy as np
A = np.array([
    [5, 8, 2, 7],
    [1, 9, 4, 3],
    [6, 0, 11, 10],
    [12, 13, 14, 15]])

print(A[1, :])
print(A[:, 2])
print(A[1:3, 1:3])

[1 9 4 3]
[ 2  4 11 14]
[[ 9  4]
 [ 0 11]]


In [5]:
import numpy as np
scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 65, 72]
])

scores[:, 1] += 5
scores[0, :] = [100, 100, 100]
scores[:, 2] = 0

print(scores)


[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [6]:
import numpy as np

A = np.array([[2, 1], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([2, 4])

print(np.multiply(A, B))
print(A @ B)
print(A * v)


[[10  6]
 [21 32]]
[[17 20]
 [43 50]]
[[ 4  4]
 [ 6 16]]


In [7]:
import numpy as np

np.random.seed(0)
M = np.random.randint(-5, 6, size=(4, 4))
print("M:", M)

u, counts = np.unique(M, return_counts=True)
print("Unique values:", u)
print("Counts:", counts)

a = np.array([
    [1, 0, 0],
    [1, 0, 0],
    [2, 3, 4]])

unique_rows = np.unique(a, axis=0)
print("Unique rows of a:\n", unique_rows)


M: [[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]
Unique values: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Counts: [1 1 1 3 1 2 1 2 2 1 1]
Unique rows of a:
 [[1 0 0]
 [2 3 4]]


In [9]:
import numpy as np

x = np.array([2, 0, 1, 5, 4, 1, 9])
A = np.array([[3, 8, 1], [6, 2, 9]])

sorted_indices = np.argsort(x)
sorted_x = x[sorted_indices]
print("Sorted x:", sorted_x)
print("Indices after sorting:", sorted_indices)

min_value_location = np.unravel_index(np.argmin(A), A.shape)
print("Minimum value location in A (row, col):", min_value_location)

indices_of_3 = np.where(x == 3)
print("Indices where x is 3:", indices_of_3)

split_x = np.split(x, [2, 5])  
print("Split x:", split_x)

expanded_x = np.expand_dims(x, axis=0)  
expanded_x_back = np.squeeze(expanded_x, axis=0)  
print("Expanded x shape:", expanded_x.shape)
print("Expanded back x shape:", expanded_x_back.shape)

Sorted x: [0 1 1 2 4 5 9]
Indices after sorting: [1 2 5 0 4 3 6]
Minimum value location in A (row, col): (np.int64(0), np.int64(2))
Indices where x is 3: (array([], dtype=int64),)
Split x: [array([2, 0]), array([1, 5, 4]), array([1, 9])]
Expanded x shape: (1, 7)
Expanded back x shape: (7,)
